production:
  server: jabber.domain.com
  port: 5560
  component_jid: chat.domain.com
  password: secret
  default_user: somebot
  debug: true

development:
  server: localhost
  port: 5560
  component_jid: chat.localhost
  password: secret
  default_user: somebot
  debug: true

test:

qa:
